

<section class="container hero is-medium" id="background-image">
  <div class="hero-body">
    <div class="title">
      <h1
        id="mainTitle"
        class="title has-text-right is-size-1 has-text-centered-mobile"
        style="font-size: 3vw;"
      >
        LetMeExplain
      </h1>
      <div
        id="descripTitle"
        class="subtitle has-text-right is-size-3 has-text-centered-mobile"
      >
        A new feedback app for<br /> converting crass <br /> and vulgar comments
        <br />into constructive criticism.
      </div>
    </div>
  </div>
</section>
<!----------------->
<section class="container p-3">
  <div class="columns">
    <div class="column has-text-centered">
      <div class="notification is-warning">
        <div class="title">
          <h1>Great for small businesses</h1>
        </div>
        <p class="is-size-6">
          LetMeExplain is a great tool for small businesses to get feedback from
          their customers.
        </p>
      </div>
    </div>
    <div class="column has-text-centered">
      <div class="notification is-info">
        <div class="title">
          <h1>Great for Hotels</h1>
        </div>
        <p class="is-size-6">
          LetMeExplain can obtain realtime responses from users by using our
          immediate chat app*. This will connect to users in realtime and enable
          admin to respond to users.
        </p>
      </div>
    </div>
    <div class="column has-text-centered">
      <div class="notification is-success">
        <div class="title">
          <h1>Great for Websites</h1>
        </div>
        <p class="is-size-6">
          LetMeExplain can be integrated into any website. Enabling realtime
          comments of users to be sent to the admin of the website by email,
          text, or chat*.
        </p>
      </div>
    </div>
  </div>
</section>
<!----------------------->
<section class="section is-medium">
  <div class="container">
    <div class="columns is-multiline">
      <div class="column is-one-third">
        <article class="media">
          <figure class="media-left">
            <!---->
            <span class="icon has-text-warning">
              <i class="fa-solid fa-2xl fa-city" />
            </span>
          </figure>
          <div class="media-content">
            <div class="content">
              <h1 class="title is-size-4 has-text-centered">
                Community Outreach
              </h1>
              <p class="subtitle is-size-5 has-text-black has-text-centered">
                Get your neighborhood engaged in detailed interaction with you
                and your business. Get realistic feedback, but with educated and
                constructive criticism generated by AI.
              </p>
            </div>
          </div>
        </article>
      </div>
      <div class="column is-one-third">
        <article class="media">
          <figure class="media-left">
            <!---->
            <span class="icon has-text-success">
              <i class="fa-regular fa-2xl fa-comment-dots" />
            </span>
          </figure>
          <div class="media-content">
            <div class="content">
              <h1 class="title is-size-4 has-text-centered">
                Interpersonal Interaction
              </h1>
              <p class="subtitle is-size-5 has-text-black has-text-centered">
                You can opt to have your customers interact with you directly.
                This will allow you to respond to their comments and questions
                in realtime with our chat app*.
              </p>
            </div>
          </div>
        </article>
      </div>
      <div class="column is-one-third">
        <article class="media">
          <figure class="media-left">
            <!---->
            <span class="icon has-text-link">
              <i class="fa-solid fa-2xl fa-robot" />
            </span>
          </figure>
          <div class="media-content">
            <div class="content">
              <h1 class="title is-size-4 has-text-centered">
                Artificial Intelligence
              </h1>
              <p class="subtitle is-size-5 has-text-black has-text-centered">
                AI will be used to convert crass and vulgar comments into
                constructive criticism. This will allow you to get realistic
                feedback from your customers without the vulgarity.
              </p>
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
</section>
<!--------------->
<section class="section is-medium has-background-link">
  <div class="container has-text-centered">
    <h1 class="title is-1 has-text-white">
      Get Feedback from Customers Today!
    </h1>
    <h2 class="subtitle md:is-3 has-text-white">
      constructive criticism that can maximize ROI
    </h2>
    <!-- <a class="button is-light is-medium" href="/signup">Join Now</a> -->
  </div>
</section>
<!-------------------->
<section class="section">
  <div class="container has-text-right">
    <p>*These are premium features. Contact us for more information.</p>
  </div>
</section>
<!-------------------------->
<!-- <section>
  <div class="container md:has-text-centered has-text-centered p-3">
    <h1 class="title is-1 has-text-black">Investors</h1>
    <h2 class="subtitle is-3 has-text-black">
      LetMeExplain is looking for investors to help us grow.
    </h2>
    <a class="button is-light is-medium" href="/investors">Learn More</a>
  </div>
</section>
<br /> -->

<style>
  #background-image:before {
    content: "Man screaming - a depiction of customer feedback";
    visibility: hidden;
  }

  #background-image {
    background-image: url("../src/lib/images/man-screaming.webp");
    background-position: left;
    background-repeat: no-repeat;
    background-size: 700px;
  }
  #mainTitle {
    text-shadow: 1px 2px 2px #000000;
  }
  #descripTitle {
    text-shadow: 1px 2px 2px #000000;
  }

  @media screen and (min-width: 1024px) {
    /* Apply to desktop and up */
    #mainTitle,
    .subtitle {
      color: black;
    }
  }

  @media screen and (max-width: 1023px) {
    /* Apply to mobile */
    #mainTitle,
    .subtitle {
      color: white;
    }
  }
</style>
